- name: install apache2 package in ubuntu
  tags: apache,apache2,ubuntu,httpd,amazon
  package:
    name: 
      - "{{apache_package_name}}"
      - "{{php_package_name}}"
    state: present

- name: install httpd package in amazon linux
  tags: apache,httpd,amazon
  service:
    name: "{{apache_service}}"
    state: started
    enabled: yes

- name: Copy default file to server
  tags: apache,httpd,amazon,ubuntu
  copy:
    src: default.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
